### ISSUE TITLE
disable spinners?

### ISSUE THREAD

**Issue by tylerecouture** [Tartarus762/jquery-duration-picker#5]
Is there a way to disable the spinner controls and just have text inputs? Kind of like your demo image? Thanks!

**Comment by Tartarus762** [comment]
In the demo image, the spinners are simply not visible until you focus the input. The spinner is visible because they are inputs of type number and are added by the browser. I can add an option to change the input type which is probably valuable to have anyway. It will be fixed in the next commit.

**Comment by tylerecouture** [comment]
I'm using it with DJango's [DurationField](https://docs.djangoproject.com/en/1.10/ref/forms/fields/#durationfield) which stores the data as text in the format: "dd hh:mm:ss.sssssss".  I modified your js to read and write this format and it integrates beautifully with django now (which is currently lacking a widget for its DurationField).  If you're interested, I can clean it up and try a PR (I'm new at this).  If not interested, no problem. Thanks for the great plugin!

**Comment by Tartarus762** [comment]
You can certainly make a pull request, if I don't think it lines up with my goals for the plugin, I'll reject it, but I'm certainly interested to see it. Interestingly, I actually made this for use with Django as well, albeit, as slightly different use case.

Alternatively, you could make a fork for your specific use-case.

Anyway, I added a basic way to change input type and since you indicated that you have solved the issue, I'll mark this as closed.
